In [1]:
import numpy as np

In [2]:
b = np.array([[8, 0], [-8, 0]])
l = np.array([40, 40])
m = np.array([50, 50])
x = np.array([10, 55])

In [3]:
p = 2 * l * (x[0] - b[:,0])
q = 2 * l * (x[1] - b[:,1])
r = (x[0] - b[:,0])**2 + (x[1] - b[:,1])**2 + l**2 - m**2

In [4]:
p

array([ 160, 1440])

In [5]:
q

array([4400, 4400])

In [6]:
r

array([2129, 2449])

In [7]:
cos = [(p*r + q*np.sqrt(p**2 + q**2 -r**2))/(p**2 + q**2), (p*r - q*np.sqrt(p**2 + q**2 -r**2))/(p**2 + q**2)]
sin = [(q*r - p*np.sqrt(p**2 + q**2 -r**2))/(p**2 + q**2), (q*r + p*np.sqrt(p**2 + q**2 -r**2))/(p**2 + q**2)]

In [8]:
sin

[array([0.45141587, 0.23878541]), array([0.51503346, 0.7667013 ])]

In [9]:
cos

[array([0.89231369, 0.97107236]), array([-0.85717008, -0.64200398])]

In [10]:
thete1 = [np.arccos(cos[0][0]) * 360 / (2*np.pi), np.arccos(cos[1][0]) * 360 / (2*np.pi)]
thete2 = [np.arccos(cos[0][1]) * 360 / (2*np.pi), np.arccos(cos[1][1]) * 360 / (2*np.pi)]

In [11]:
thete1[0]

26.8345607840961

In [12]:
thete2[1]

129.9414141648851